# Exercise 02 -  OLAP Cubes - Grouping Sets

Start by connecting to the database by running the cells below. If you are coming back to this exercise, then uncomment and run the first cell to recreate the database. If you recently completed the slicing and dicing exercise, then skip to the second cell.

In [ ]:
# !PGPASSWORD=student createdb -h 127.0.0.1 -U student pagila_star
# !PGPASSWORD=student psql -q -h 127.0.0.1 -U student -d pagila_star -f Data/pagila-star.sql

### Connect to the local database where Pagila is loaded

In [1]:
import sql
%load_ext sql

DB_ENDPOINT = "127.0.0.1"
DB = 'pagila_star'
DB_USER = 'student'
DB_PASSWORD = 'student'
DB_PORT = '5432'

# postgresql://username:password@host:port/database
conn_string = "postgresql://{}:{}@{}:{}/{}" \
                        .format(DB_USER, DB_PASSWORD, DB_ENDPOINT, DB_PORT, DB)

print(conn_string)
%sql $conn_string

postgresql://student:student@127.0.0.1:5432/pagila_star

'Connected: student@pagila_star'

### Star Schema

<img src="pagila-star.png" width="50%"/>

# Grouping Sets
- It happens often that for 3 dimensions, you want to aggregate a fact:
    - by nothing (total)
    - then by the 1st dimension
    - then by the 2nd 
    - then by the 3rd 
    - then by the 1st and 2nd
    - then by the 2nd and 3rd
    - then by the 1st and 3rd
    - then by the 1st and 2nd and 3rd
    
- Since this is very common, and in all cases, we are iterating through all the fact table anyhow, there is a more clever way to do that using the SQL grouping statement "GROUPING SETS"

## Total Revenue

TODO: Write a query that calculates total revenue (sales_amount)

In [3]:
%%sql
SELECT sum(sales_amount) as revenue
FROM factsales

 * postgresql://student:***@127.0.0.1:5432/pagila_star
1 rows affected.

[(Decimal('67416.51'),)]

## Revenue by Country
TODO: Write a query that calculates total revenue (sales_amount) by country

In [5]:
%%sql
SELECT c.country, sum(f.sales_amount) as revenue
FROM factsales as f
JOIN dimcustomer as c ON f.customer_key = c.customer_key
GROUP BY c.country

 * postgresql://student:***@127.0.0.1:5432/pagila_star
108 rows affected.

[('Cambodia', Decimal('191.47')),
 ('Turkey', Decimal('1662.12')),
 ('Germany', Decimal('831.04')),
 ('Chad', Decimal('135.68')),
 ('Madagascar', Decimal('93.78')),
 ('France', Decimal('374.04')),
 ('Iraq', Decimal('111.73')),
 ('Colombia', Decimal('709.41')),
 ('Japan', Decimal('3471.74')),
 ('American Samoa', Decimal('71.80')),
 ('Virgin Islands, U.S.', Decimal('122.68')),
 ('Vietnam', Decimal('746.28')),
 ('Kuwait', Decimal('111.74')),
 ('Ecuador', Decimal('390.13')),
 ('Nepal', Decimal('116.78')),
 ('Cameroon', Decimal('200.46')),
 ('Saudi Arabia', Decimal('523.79')),
 ('Bangladesh', Decimal('402.05')),
 ('Lithuania', Decimal('73.76')),
 ('Netherlands', Decimal('586.66')),
 ('Yugoslavia', Decimal('259.43')),
 ('Gambia', Decimal('129.70')),
 ('Nigeria', Decimal('1511.48')),
 ('Dominican Republic', Decimal('318.23')),
 ('Faroe Islands', Decimal('114.72')),
 ('Egypt', Decimal('694.39')),
 ('Zambia', Decimal('134.67')),
 ('United States', Decimal('4110.32')),
 ('Argentina', Decimal('1434.48')),
 ('Slovakia', Decimal('89.74')),
 ('Angola', Decimal('215.48')),
 ('Russian Federation', Decimal('3045.87')),
 ('Oman', Decimal('187.50')),
 ('Turkmenistan', Decimal('136.73')),
 ('Afghanistan', Decimal('67.82')),
 ('Czech Republic', Decimal('133.71')),
 ('Liechtenstein', Decimal('114.72')),
 ('Ethiopia', Decimal('91.77')),
 ('Azerbaijan', Decimal('245.43')),
 ('Brazil', Decimal('3200.52')),
 ('Israel', Decimal('422.01')),
 ('Senegal', Decimal('100.75')),
 ('Chile', Decimal('328.29')),
 ('New Zealand', Decimal('92.76')),
 ('Hungary', Decimal('111.71')),
 ('Mozambique', Decimal('344.20')),
 ('Mexico', Decimal('3307.04')),
 ('Finland', Decimal('101.74')),
 ('Taiwan', Decimal('1210.94')),
 ('Sri Lanka', Decimal('116.70')),
 ('Thailand', Decimal('419.04')),
 ('Estonia', Decimal('115.70')),
 ('Latvia', Decimal('262.40')),
 ('Venezuela', Decimal('683.30')),
 ('Peru', Decimal('468.88')),
 ('Holy See (Vatican City State)', Decimal('152.66')),
 ('Runion', Decimal('216.54')),
 ('Anguilla', Decimal('106.65')),
 ('Bahrain', Decimal('112.75')),
 ('Algeria', Decimal('383.10')),
 ('Malaysia', Decimal('369.15')),
 ('Iran', Decimal('950.75')),
 ('Spain', Decimal('606.58')),
 ('Ukraine', Decimal('730.42')),
 ('Tonga', Decimal('73.82')),
 ('South Korea', Decimal('574.65')),
 ('Belarus', Decimal('277.34')),
 ('French Guiana', Decimal('103.78')),
 ('Hong Kong', Decimal('142.70')),
 ('Malawi', Decimal('123.72')),
 ('Nauru', Decimal('148.69')),
 ('Romania', Decimal('235.38')),
 ('North Korea', Decimal('113.69')),
 ('Puerto Rico', Decimal('254.39')),
 ('Canada', Decimal('593.63')),
 ('China', Decimal('5802.73')),
 ('Austria', Decimal('307.22')),
 ('Moldova', Decimal('127.66')),
 ('South Africa', Decimal('1204.15')),
 ('Kenya', Decimal('253.46')),
 ('Poland', Decimal('877.97')),
 ('Kazakstan', Decimal('198.48')),
 ('United Kingdom', Decimal('924.80')),
 ('Brunei', Decimal('113.65')),
 ('Tunisia', Decimal('78.77')),
 ('Italy', Decimal('831.11')),
 ('Pakistan', Decimal('525.72')),
 ('Sweden', Decimal('144.66')),
 ('Armenia', Decimal('118.75')),
 ('Greece', Decimal('232.46')),
 ('India', Decimal('6630.27')),
 ('Yemen', Decimal('510.83')),
 ('Paraguay', Decimal('275.38')),
 ('Myanmar', Decimal('194.48')),
 ('Philippines', Decimal('2381.32')),
 ('Morocco', Decimal('307.29')),
 ('Greenland', Decimal('137.66')),
 ('Switzerland', Decimal('252.39')),
 ('Indonesia', Decimal('1510.33')),
 ('Tuvalu', Decimal('120.74')),
 ('Saint Vincent and the Grenadines', Decimal('96.75')),
 ('Bolivia', Decimal('183.53')),
 ('Congo, The Democratic Republic of the', Decimal('212.50')),
 ('Sudan', Decimal('227.46')),
 ('United Arab Emirates', Decimal('333.16')),
 ('Tanzania', Decimal('341.17')),
 ('French Polynesia', Decimal('235.46')),
 ('Bulgaria', Decimal('204.50'))]

## Revenue by Month
TODO: Write a query that calculates total revenue (sales_amount) by month

In [9]:
%%time
%%sql


SELECT d.month, sum(f.sales_amount) as revenue
FROM factsales as f
JOIN dimdate as d ON f.date_key = d.date_key
GROUP BY d.month

 * postgresql://student:***@127.0.0.1:5432/pagila_star
5 rows affected.
CPU times: user 3.29 ms, sys: 509 µs, total: 3.8 ms
Wall time: 14 ms

[(1, Decimal('4824.43')),
 (3, Decimal('23886.56')),
 (4, Decimal('28559.46')),
 (2, Decimal('9631.88')),
 (5, Decimal('514.18'))]

## Revenue by Month & Country
TODO: Write a query that calculates total revenue (sales_amount) by month and country. Sort the data by month, country, and revenue in descending order. The first few rows of your output should match the table below.

In [10]:
%%sql
SELECT d.month, c.country, sum(f.sales_amount) as revenue
FROM factsales as f
JOIN dimdate as d ON f.date_key = d.date_key
JOIN dimcustomer as c ON f.customer_key = c.customer_key
GROUP BY d.month, c.country

 * postgresql://student:***@127.0.0.1:5432/pagila_star
484 rows affected.

[(1, 'Virgin Islands, U.S.', Decimal('0.99')),
 (4, 'Morocco', Decimal('100.74')),
 (2, 'Bahrain', Decimal('30.95')),
 (1, 'Zambia', Decimal('12.97')),
 (2, 'Oman', Decimal('32.92')),
 (1, 'Latvia', Decimal('12.97')),
 (1, 'United Kingdom', Decimal('73.84')),
 (2, 'Iraq', Decimal('12.97')),
 (2, 'Egypt', Decimal('121.73')),
 (5, 'United Arab Emirates', Decimal('4.99')),
 (3, 'Finland', Decimal('45.89')),
 (3, 'Chile', Decimal('149.70')),
 (4, 'Greece', Decimal('90.81')),
 (5, 'Mexico', Decimal('13.94')),
 (2, 'Mozambique', Decimal('14.95')),
 (3, 'Morocco', Decimal('126.72')),
 (1, 'China', Decimal('455.91')),
 (1, 'Faroe Islands', Decimal('6.99')),
 (1, 'Gambia', Decimal('14.97')),
 (1, 'Russian Federation', Decimal('225.40')),
 (1, 'Malaysia', Decimal('30.94')),
 (3, 'Greece', Decimal('82.80')),
 (4, 'Chile', Decimal('101.77')),
 (4, 'Finland', Decimal('32.90')),
 (1, 'Congo, The Democratic Republic of the', Decimal('43.92')),
 (3, 'Sri Lanka', Decimal('46.88')),
 (2, 'Armenia', Decimal('12.98')),
 (3, 'Vietnam', Decimal('278.35')),
 (2, 'Thailand', Decimal('63.84')),
 (3, 'Philippines', Decimal('905.98')),
 (3, 'India', Decimal('2547.23')),
 (3, 'Anguilla', Decimal('44.87')),
 (3, 'Holy See (Vatican City State)', Decimal('57.88')),
 (2, 'Dominican Republic', Decimal('33.91')),
 (4, 'Liechtenstein', Decimal('49.85')),
 (5, 'Germany', Decimal('14.95')),
 (3, 'South Korea', Decimal('177.64')),
 (1, 'Turkey', Decimal('120.73')),
 (2, 'Saint Vincent and the Grenadines', Decimal('15.96')),
 (2, 'Paraguay', Decimal('34.90')),
 (3, 'American Samoa', Decimal('7.96')),
 (1, 'Peru', Decimal('40.91')),
 (4, 'Bangladesh', Decimal('163.61')),
 (1, 'Nauru', Decimal('4.99')),
 (1, 'Italy', Decimal('51.89')),
 (2, 'Kuwait', Decimal('36.92')),
 (3, 'Iran', Decimal('350.22')),
 (4, 'Israel', Decimal('203.54')),
 (1, 'Tanzania', Decimal('18.95')),
 (4, 'United States', Decimal('1662.20')),
 (2, 'Nigeria', Decimal('177.60')),
 (3, 'Liechtenstein', Decimal('28.94')),
 (4, 'South Korea', Decimal('291.31')),
 (4, 'Anguilla', Decimal('37.86')),
 (4, 'Holy See (Vatican City State)', Decimal('46.87')),
 (2, 'Indonesia', Decimal('239.42')),
 (4, 'Philippines', Decimal('928.65')),
 (4, 'India', Decimal('2757.46')),
 (2, 'Venezuela', Decimal('140.68')),
 (4, 'Vietnam', Decimal('308.31')),
 (4, 'Sri Lanka', Decimal('45.88')),
 (3, 'United States', Decimal('1519.45')),
 (2, 'Sudan', Decimal('27.90')),
 (4, 'Iran', Decimal('410.05')),
 (3, 'Israel', Decimal('121.70')),
 (3, 'Bangladesh', Decimal('154.64')),
 (1, 'Azerbaijan', Decimal('20.97')),
 (5, 'Hungary', Decimal('0.99')),
 (4, 'American Samoa', Decimal('39.89')),
 (2, 'Chad', Decimal('9.98')),
 (5, 'United Kingdom', Decimal('11.96')),
 (2, 'Iran', Decimal('129.65')),
 (3, 'Kuwait', Decimal('53.87')),
 (4, 'Sudan', Decimal('105.76')),
 (3, 'Nigeria', Decimal('542.77')),
 (5, 'Latvia', Decimal('2.99')),
 (4, 'Chad', Decimal('48.89')),
 (3, 'Saint Vincent and the Grenadines', Decimal('17.94')),
 (5, 'Zambia', Decimal('0.99')),
 (3, 'Paraguay', Decimal('91.78')),
 (2, 'American Samoa', Decimal('23.95')),
 (4, 'Venezuela', Decimal('292.27')),
 (2, 'India', Decimal('832.92')),
 (2, 'Philippines', Decimal('359.17')),
 (4, 'Indonesia', Decimal('606.61')),
 (2, 'Holy See (Vatican City State)', Decimal('41.93')),
 (2, 'Anguilla', Decimal('16.95')),
 (1, 'Mexico', Decimal('263.37')),
 (3, 'Dominican Republic', Decimal('134.65')),
 (2, 'South Korea', Decimal('54.84')),
 (2, 'Sri Lanka', Decimal('10.97')),
 (3, 'Armenia', Decimal('31.93')),
 (2, 'Vietnam', Decimal('116.74')),
 (3, 'Thailand', Decimal('147.68')),
 (1, 'United Arab Emirates', Decimal('12.95')),
 (5, 'China', Decimal('40.87')),
 (4, 'Saint Vincent and the Grenadines', Decimal('46.88')),
 (4, 'Paraguay', Decimal('146.72')),
 (3, 'Chad', Decimal('63.85')),
 (2, 'United States', Decimal('590.48')),
 (4, 'Nigeria', Decimal('647.43')),
 (3, 'Sudan', Decimal('68.85')),
 (4, 'Kuwait', Decimal('14.97')),
 (2, 'Israel', Decimal('53.89')),
 (1, 'Pakistan', Decimal('51.88')),
 (2, 'Bangladesh', Decimal('60.86')),
 (4, 'Thailand', Decimal('183.58')),
 (4, 'Armenia', Decimal('70.85')),
 (5, 'Malaysia', Decimal('0.99')),
 (2, 'Liechtenstein', Decimal('20.95')),
 (4, 'Dominican Republic', Decimal('135.70')),
 (5, 'Russian Federation', Decimal('7.96')),
 (3, 'Indonesia', Decimal('522.63')),
 (5, 'Faroe Islands', Decimal('0.99')),
 (1, 'Poland', Decimal('54.89')),
 (3, 'Venezuela', Decimal('219.45')),
 (1, 'Germany', Decimal('89.80')),
 (3, 'Mozambique', Decimal('104.74')),
 (2, 'Finland', Decimal('18.96')),
 (2, 'Chile', Decimal('51.87')),
 (5, 'Tanzania', Decimal('4.99')),
 (3, 'Oman', Decimal('42.89')),
 (5, 'Italy', Decimal('3.98')),
 (3, 'Iraq', Decimal('31.91')),
 (3, 'Egypt', Decimal('256.40')),
 (5, 'Peru', Decimal('4.99')),
 (3, 'Bahrain', Decimal('17.96')),
 (5, 'Turkey', Decimal('10.97')),
 (2, 'Greece', Decimal('29.94')),
 (1, 'Angola', Decimal('27.93')),
 (4, 'Mozambique', Decimal('195.56')),
 (4, 'Bahrain', Decimal('56.86')),
 (2, 'Morocco', Decimal('41.90')),
 (5, 'Azerbaijan', Decimal('0.99')),
 (4, 'Egypt', Decimal('281.35')),
 (4, 'Iraq', Decimal('65.86')),
 (4, 'Oman', Decimal('80.76')),
 (2, 'French Polynesia', Decimal('18.95')),
 (4, 'Estonia', Decimal('27.92')),
 (2, 'Switzerland', Decimal('30.94')),
 (2, 'Ukraine', Decimal('79.80')),
 (4, 'Senegal', Decimal('24.93')),
 (1, 'Tuvalu', Decimal('26.96')),
 (4, 'Greenland', Decimal('58.85')),
 (2, 'Algeria', Decimal('60.88')),
 (5, 'Puerto Rico', Decimal('0.99')),
 (4, 'Brunei', Decimal('59.81')),
 (3, 'Moldova', Decimal('45.89')),
 (1, 'North Korea', Decimal('5.98')),
 (2, 'Taiwan', Decimal('171.60')),
 (4, 'Turkmenistan', Decimal('37.90')),
 (1, 'Madagascar', Decimal('0.99')),
 (3, 'Senegal', Decimal('44.90')),
 (1, 'Nepal', Decimal('15.97')),
 (3, 'Estonia', Decimal('51.86')),
 (1, 'Bolivia', Decimal('4.97')),
 (1, 'Yemen', Decimal('15.94')),
 (3, 'Turkmenistan', Decimal('53.92')),
 (2, 'Spain', Decimal('68.85')),
 (4, 'Moldova', Decimal('65.82')),
 (3, 'Brunei', Decimal('29.90')),
 (1, 'Malawi', Decimal('1.99')),
 (3, 'Greenland', Decimal('56.88')),
 (5, 'Canada', Decimal('3.98')),
 (4, 'Tunisia', Decimal('55.85')),
 (3, 'Sweden', Decimal('48.87')),
 (2, 'Colombia', Decimal('72.83')),
 (2, 'Japan', Decimal('488.83')),
 (2, 'Bulgaria', Decimal('42.89')),
 (5, 'South Africa', Decimal('4.99')),
 (5, 'Belarus', Decimal('2.99')),
 (3, 'Kenya', Decimal('85.82')),
 (4, 'France', Decimal('199.55')),
 (4, 'New Zealand', Decimal('35.88')),
 (2, 'Cameroon', Decimal('33.91')),
 (1, 'Czech Republic', Decimal('0.99')),
 (2, 'Romania', Decimal('26.92')),
 (4, 'Sweden', Decimal('60.87')),
 (3, 'Tunisia', Decimal('16.94')),
 (1, 'Tonga', Decimal('8.98')),
 (5, 'Lithuania', Decimal('4.99')),
 (2, 'Kazakstan', Decimal('33.90')),
 (1, 'Cambodia', Decimal('11.96')),
 (3, 'New Zealand', Decimal('35.92')),
 (3, 'France', Decimal('80.76')),
 (1, 'Argentina', Decimal('81.78')),
 (4, 'Kenya', Decimal('97.79')),
 (1, 'Runion', Decimal('4.99')),
 (5, 'Brazil', Decimal('22.93')),
 (5, 'Netherlands', Decimal('0.99')),
 (5, 'Saudi Arabia', Decimal('3.98')),
 (1, 'Austria', Decimal('22.92')),
 (1, 'Ecuador', Decimal('20.95')),
 (2, 'Kenya', Decimal('58.89')),
 (4, 'Kazakstan', Decimal('96.76')),
 (3, 'Cameroon', Decimal('71.80')),
 (3, 'Bulgaria', Decimal('78.80')),
 (2, 'Sweden', Decimal('29.93')),
 (4, 'Romania', Decimal('119.69')),
 (3, 'Japan', Decimal('1253.03')),
 (3, 'Colombia', Decimal('252.46')),
 (1, 'Slovakia', Decimal('8.97')),
 (1, 'Puerto Rico', Decimal('15.95')),
 (5, 'Yemen', Decimal('2.99')),
 (5, 'Bolivia', Decimal('2.99')),
 (4, 'Bulgaria', Decimal('71.84')),
 (4, 'Cameroon', Decimal('73.81')),
 (3, 'Kazakstan', Decimal('61.85')),
 (1, 'French Guiana', Decimal('5.98')),
 (2, 'New Zealand', Decimal('13.97')),
 (2, 'France', Decimal('52.82')),
 (2, 'Tunisia', Decimal('4.99')),
 (4, 'Japan', Decimal('1418.62')),
 (4, 'Colombia', Decimal('321.28')),
 (3, 'Romania', Decimal('71.81')),
 (2, 'Moldova', Decimal('15.95')),
 (3, 'Taiwan', Decimal('398.94')),
 (1, 'Yugoslavia', Decimal('25.94')),
 (4, 'Spain', Decimal('257.41')),
 (1, 'Canada', Decimal('33.93')),
 (3, 'Algeria', Decimal('111.72')),
 (1, 'Myanmar', Decimal('14.95')),
 (3, 'French Polynesia', Decimal('91.81')),
 (3, 'Switzerland', Decimal('68.81')),
 (1, 'Belarus', Decimal('5.98')),
 (3, 'Ukraine', Decimal('247.44')),
 (1, 'South Africa', Decimal('99.76')),
 (2, 'Brunei', Decimal('12.96')),
 (1, 'Lithuania', Decimal('9.98')),
 (2, 'Greenland', Decimal('3.99')),
 (4, 'Algeria', Decimal('170.60')),
 (2, 'Turkmenistan', Decimal('31.93')),
 (3, 'Spain', Decimal('213.49')),
 (4, 'Taiwan', Decimal('565.63')),
 (1, 'Netherlands', Decimal('25.94')),
 (4, 'Ukraine', Decimal('348.29')),
 (1, 'Saudi Arabia', Decimal('65.87')),
 (4, 'Switzerland', Decimal('140.68')),
 (4, 'French Polynesia', Decimal('85.79')),
 (2, 'Estonia', Decimal('25.94')),
 (1, 'Brazil', Decimal('210.50')),
 (5, 'Argentina', Decimal('26.91')),
 (2, 'Senegal', Decimal('25.93')),
 (5, 'Cambodia', Decimal('9.96')),
 (3, 'Russian Federation', Decimal('959.68')),
 (5, 'Indonesia', Decimal('5.98')),
 (3, 'Faroe Islands', Decimal('44.89')),
 (3, 'Gambia', Decimal('58.87')),
 (5, 'Venezuela', Decimal('5.98')),
 (2, 'Angola', Decimal('35.92')),
 (3, 'Congo, The Democratic Republic of the', Decimal('94.77')),
 (3, 'Malaysia', Decimal('155.67')),
 (1, 'Greece', Decimal('27.92')),
 (4, 'Latvia', Decimal('126.70')),
 (4, 'United Kingdom', Decimal('380.10')),
 (3, 'China', Decimal('2061.94')),
 (2, 'Hungary', Decimal('24.95')),
 (4, 'Virgin Islands, U.S.', Decimal('68.82')),
 (4, 'Zambia', Decimal('54.86')),
 (4, 'Afghanistan', Decimal('37.92')),
 (1, 'Morocco', Decimal('32.94')),
 (5, 'Armenia', Decimal('2.99')),
 (4, 'Malaysia', Decimal('133.67')),
 (4, 'Congo, The Democratic Republic of the', Decimal('44.90')),
 (1, 'Finland', Decimal('3.99')),
 (1, 'Chile', Decimal('24.95')),
 (2, 'Hong Kong', Decimal('37.94')),
 (5, 'Thailand', Decimal('5.98')),
 (4, 'Faroe Islands', Decimal('50.88')),
 (4, 'Gambia', Decimal('44.88')),
 (2, 'Germany', Decimal('133.71')),
 (4, 'Russian Federation', Decimal('1426.89')),
 (3, 'Afghanistan', Decimal('24.93')),
 (3, 'Zambia', Decimal('47.91')),
 (3, 'Virgin Islands, U.S.', Decimal('25.94')),
 (4, 'China', Decimal('2404.99')),
 (3, 'United Kingdom', Decimal('276.28')),
 (5, 'Nigeria', Decimal('8.97')),
 (3, 'Latvia', Decimal('70.84')),
 (5, 'Kuwait', Decimal('0.99')),
 (2, 'Pakistan', Decimal('81.81')),
 (4, 'Nauru', Decimal('60.87')),
 (4, 'Peru', Decimal('177.54')),
 (1, 'Bangladesh', Decimal('19.95')),
 (3, 'Azerbaijan', Decimal('87.79')),
 (1, 'United States', Decimal('309.30')),
 (4, 'Tanzania', Decimal('145.68')),
 (4, 'Italy', Decimal('339.22')),
 (1, 'Israel', Decimal('39.89')),
 (4, 'Turkey', Decimal('742.27')),
 (2, 'Poland', Decimal('161.66')),
 (1, 'Liechtenstein', Decimal('14.98')),
 (3, 'Turkey', Decimal('581.67')),
 (5, 'Bahrain', Decimal('2.99')),
 (1, 'Iran', Decimal('55.84')),
 (3, 'Italy', Decimal('314.26')),
 (5, 'Oman', Decimal('4.99')),
 (3, 'Tanzania', Decimal('136.65')),
 (4, 'Azerbaijan', Decimal('109.75')),
 (3, 'Peru', Decimal('173.61')),
 (3, 'Nauru', Decimal('69.86')),
 (5, 'Iraq', Decimal('0.99')),
 (1, 'Vietnam', Decimal('33.91')),
 (2, 'United Arab Emirates', Decimal('63.83')),
 (1, 'Sri Lanka', Decimal('12.97')),
 (1, 'Holy See (Vatican City State)', Decimal('5.98')),
 (1, 'Anguilla', Decimal('6.97')),
 (2, 'Mexico', Decimal('504.83')),
 (1, 'South Korea', Decimal('46.88')),
 (1, 'Philippines', Decimal('161.62')),
 (1, 'India', Decimal('429.89')),
 (5, 'Greece', Decimal('0.99')),
 (4, 'United Arab Emirates', Decimal('161.62')),
 (1, 'Venezuela', Decimal('24.92')),
 (3, 'Poland', Decimal('272.30')),
 (4, 'Mexico', Decimal('1386.79')),
 (1, 'Indonesia', Decimal('135.69')),
 (1, 'Chad', Decimal('12.96')),
 (5, 'Morocco', Decimal('4.99')),
 (3, 'Pakistan', Decimal('208.50')),
 (2, 'Azerbaijan', Decimal('25.93')),
 (1, 'Sudan', Decimal('24.95')),
 (1, 'Dominican Republic', Decimal('13.97')),
 (3, 'Mexico', Decimal('1138.11')),
 (4, 'Poland', Decimal('389.12')),
 (1, 'Thailand', Decimal('17.96')),
 (3, 'United Arab Emirates', Decimal('89.77')),
 (1, 'Kuwait', Decimal('4.99')),
 (2, 'Italy', Decimal('121.76')),
 (2, 'Tanzania', Decimal('34.90')),
 (1, 'Nigeria', Decimal('134.71')),
 (2, 'Peru', Decimal('71.83')),
 (2, 'Nauru', Decimal('12.97')),
 (4, 'Pakistan', Decimal('183.53')),
 (2, 'Turkey', Decimal('206.48')),
 (1, 'Saint Vincent and the Grenadines', Decimal('15.97')),
 (1, 'Paraguay', Decimal('1.98')),
 (2, 'China', Decimal('839.02')),
 (3, 'Hungary', Decimal('23.92')),
 (5, 'Israel', Decimal('2.99')),
 (5, 'United States', Decimal('28.89')),
 (5, 'Bangladesh', Decimal('2.99')),
 (4, 'Hong Kong', Decimal('49.88')),
 (3, 'Angola', Decimal('67.83')),
 (2, 'Congo, The Democratic Republic of the', Decimal('28.91')),
 (2, 'Malaysia', Decimal('47.88')),
 (2, 'Russian Federation', Decimal('425.94')),
 (4, 'Germany', Decimal('326.21')),
 (2, 'Faroe Islands', Decimal('10.97')),
 (2, 'Gambia', Decimal('10.98')),
 (2, 'United Kingdom', Decimal('182.62')),
 (1, 'Egypt', Decimal('34.91')),
 (1, 'Oman', Decimal('25.94')),
 (2, 'Latvia', Decimal('48.90')),
 (5, 'Iran', Decimal('4.99')),
 (2, 'Afghanistan', Decimal('4.97')),
 (1, 'Bahrain', Decimal('3.99')),
 (2, 'Zambia', Decimal('17.94')),
 (4, 'Hungary', Decimal('61.85')),
 (2, 'Virgin Islands, U.S.', Decimal('26.93')),
 (5, 'Philippines', Decimal('25.90')),
 (5, 'India', Decimal('62.77')),
 (5, 'South Korea', Decimal('3.98')),
 (3, 'Germany', Decimal('266.37')),
 (1, 'Mozambique', Decimal('28.95')),
 (5, 'Vietnam', Decimal('8.97')),
 (3, 'Hong Kong', Decimal('54.88')),
 (4, 'Angola', Decimal('83.80')),
 (4, 'North Korea', Decimal('57.82')),
 (1, 'Turkmenistan', Decimal('9.99')),
 (1, 'Brunei', Decimal('5.99')),
 (2, 'Lithuania', Decimal('11.97')),
 (3, 'Malawi', Decimal('50.90')),
 (1, 'Greenland', Decimal('17.94')),
 (4, 'Tuvalu', Decimal('48.90')),
 (3, 'Madagascar', Decimal('55.88')),
 (1, 'Senegal', Decimal('4.99')),
 (3, 'Nepal', Decimal('42.93')),
 (1, 'Estonia', Decimal('9.98')),
 (3, 'Bolivia', Decimal('67.82')),
 (3, 'Yemen', Decimal('158.65')),
 (2, 'Brazil', Decimal('454.87')),
 (2, 'Netherlands', Decimal('86.83')),
 (2, 'Saudi Arabia', Decimal('37.91')),
 (4, 'Malawi', Decimal('56.87')),
 (2, 'Myanmar', Decimal('47.87')),
 (2, 'Canada', Decimal('75.80')),
 (2, 'Ethiopia', Decimal('17.96')),
 (5, 'Colombia', Decimal('14.97')),
 (3, 'North Korea', Decimal('48.90')),
 (5, 'Japan', Decimal('22.91')),
 (2, 'Yugoslavia', Decimal('30.92')),
 (5, 'Bulgaria', Decimal('0.99')),
 (2, 'South Africa', Decimal('177.58')),
 (4, 'Bolivia', Decimal('63.86')),
 (4, 'Yemen', Decimal('262.43')),
 (2, 'Belarus', Decimal('30.90')),
 (4, 'Nepal', Decimal('50.90')),
 (4, 'Madagascar', Decimal('23.94')),
 (3, 'Tuvalu', Decimal('32.91')),
 (5, 'Cameroon', Decimal('6.97')),
 (3, 'Argentina', Decimal('455.90')),
 (1, 'France', Decimal('39.92')),
 (3, 'Cambodia', Decimal('30.89')),
 (1, 'New Zealand', Decimal('6.99')),
 (2, 'French Guiana', Decimal('12.98')),
 (3, 'Austria', Decimal('126.70')),
 (3, 'Runion', Decimal('87.82')),
 (3, 'Czech Republic', Decimal('45.91')),
 (5, 'Spain', Decimal('9.98')),
 (3, 'Tonga', Decimal('25.93')),
 (5, 'French Polynesia', Decimal('8.97')),
 (5, 'Switzerland', Decimal('7.98')),
 (4, 'Runion', Decimal('100.78')),
 (4, 'Austria', Decimal('117.71')),
 (4, 'Cambodia', Decimal('101.76')),
 (2, 'Ecuador', Decimal('54.90')),
 (1, 'Kenya', Decimal('7.97')),
 (4, 'Argentina', Decimal('650.40')),
 (4, 'Tonga', Decimal('28.94')),
 (5, 'Algeria', Decimal('5.98')),
 (2, 'Puerto Rico', Decimal('32.92')),
 (5, 'Taiwan', Decimal('18.93')),
 (2, 'Slovakia', Decimal('16.96')),
 (1, 'Sweden', Decimal('4.99')),
 (4, 'Czech Republic', Decimal('70.84')),
 (4, 'Puerto Rico', Decimal('134.68')),
 (5, 'Brunei', Decimal('4.99')),
 (2, 'Tonga', Decimal('9.97')),
 (2, 'Czech Republic', Decimal('15.97')),
 (5, 'Turkmenistan', Decimal('2.99')),
 (1, 'Romania', Decimal('16.96')),
 (4, 'Slovakia', Decimal('42.88')),
 (2, 'Austria', Decimal('39.89')),
 (2, 'Runion', Decimal('22.95')),
 (2, 'Argentina', Decimal('219.49')),
 (4, 'Ecuador', Decimal('166.61')),
 (1, 'Kazakstan', Decimal('5.97')),
 (2, 'Cambodia', Decimal('36.90')),
 (3, 'French Guiana', Decimal('46.91')),
 (1, 'Colombia', Decimal('47.87')),
 (1, 'Japan', Decimal('288.35')),
 (3, 'Slovakia', Decimal('20.93')),
 (3, 'Puerto Rico', Decimal('69.85')),
 (4, 'French Guiana', Decimal('37.91')),
 (1, 'Cameroon', Decimal('13.97')),
 (3, 'Ecuador', Decimal('147.67')),
 (1, 'Bulgaria', Decimal('9.98')),
 (4, 'Belarus', Decimal('120.73')),
 (2, 'Bolivia', Decimal('43.89')),
 (3, 'Brazil', Decimal('1106.43')),
 (2, 'Yemen', Decimal('70.82')),
 (4, 'South Africa', Decimal('467.84')),
 (3, 'Netherlands', Decimal('236.46')),
 (3, 'Saudi Arabia', Decimal('179.54')),
 (2, 'Madagascar', Decimal('12.97')),
 (2, 'Nepal', Decimal('6.98')),
 (5, 'France', Decimal('0.99')),
 (4, 'Canada', Decimal('220.44')),
 (5, 'Tunisia', Decimal('0.99')),
 (4, 'Myanmar', Decimal('34.89')),
 (3, 'Lithuania', Decimal('19.92')),
 (2, 'Malawi', Decimal('13.96')),
 (1, 'Spain', Decimal('56.85')),
 (4, 'Yugoslavia', Decimal('128.73')),
 (4, 'Ethiopia', Decimal('23.92')),
 (2, 'Tuvalu', Decimal('11.97')),
 (5, 'Kenya', Decimal('2.99')),
 (1, 'Ukraine', Decimal('54.89')),
 (4, 'Saudi Arabia', Decimal('236.49')),
 (3, 'South Africa', Decimal('453.98')),
 (4, 'Netherlands', Decimal('236.44')),
 (4, 'Brazil', Decimal('1405.79')),
 (1, 'French Polynesia', Decimal('29.94')),
 (1, 'Switzerland', Decimal('3.98')),
 (3, 'Belarus', Decimal('116.74')),
 (3, 'Ethiopia', Decimal('49.89')),
 (1, 'Taiwan', Decimal('55.84')),
 (2, 'North Korea', Decimal('0.99')),
 (3, 'Yugoslavia', Decimal('73.84')),
 (1, 'Algeria', Decimal('33.92')),
 (4, 'Lithuania', Decimal('26.90')),
 (3, 'Myanmar', Decimal('96.77')),
 (3, 'Canada', Decimal('259.48'))]

<div class="p-Widget jp-RenderedHTMLCommon jp-RenderedHTML jp-mod-trusted jp-OutputArea-output jp-OutputArea-executeResult" data-mime-type="text/html"><table>
    <tbody><tr>
        <th>month</th>
        <th>country</th>
        <th>revenue</th>
    </tr>
    <tr>
        <td>1</td>
        <td>Australia</td>
        <td>2364.19</td>
    </tr>
    <tr>
        <td>1</td>
        <td>Canada</td>
        <td>2460.24</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Australia</td>
        <td>4895.10</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Canada</td>
        <td>4736.78</td>
    </tr>
    <tr>
        <td>3</td>
        <td>Australia</td>
        <td>12060.33</td>
    </tr>
</tbody></table></div>

## Revenue Total, by Month, by Country, by Month & Country All in one shot

TODO: Write a query that calculates total revenue at the various grouping levels done above (total, by month, by country, by month & country) all at once using the grouping sets function. Your output should match the table below.

In [24]:
%%sql
SELECT d.month, c.country, sum(f.sales_amount) as revenue
FROM factsales as f
JOIN dimdate as d ON f.date_key = d.date_key
JOIN dimstore as c ON f.store_key = c.store_key
GROUP BY GROUPING SETS ((), d.month, c.country, (d.month, c.country))
ORDER BY revenue DESC
LIMIT 10

 * postgresql://student:***@127.0.0.1:5432/pagila_star
10 rows affected.

[(None, None, Decimal('67416.51')),
 (None, 'Australia', Decimal('33726.77')),
 (None, 'Canada', Decimal('33689.74')),
 (4, None, Decimal('28559.46')),
 (3, None, Decimal('23886.56')),
 (4, 'Canada', Decimal('14423.39')),
 (4, 'Australia', Decimal('14136.07')),
 (3, 'Australia', Decimal('12060.33')),
 (3, 'Canada', Decimal('11826.23')),
 (2, None, Decimal('9631.88'))]

<div class="p-Widget jp-RenderedHTMLCommon jp-RenderedHTML jp-mod-trusted jp-OutputArea-output jp-OutputArea-executeResult" data-mime-type="text/html"><table>
    <tbody><tr>
        <th>month</th>
        <th>country</th>
        <th>revenue</th>
    </tr>
    <tr>
        <td>1</td>
        <td>Australia</td>
        <td>2364.19</td>
    </tr>
    <tr>
        <td>1</td>
        <td>Canada</td>
        <td>2460.24</td>
    </tr>
    <tr>
        <td>1</td>
        <td>None</td>
        <td>4824.43</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Australia</td>
        <td>4895.10</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Canada</td>
        <td>4736.78</td>
    </tr>
    <tr>
        <td>2</td>
        <td>None</td>
        <td>9631.88</td>
    </tr>
    <tr>
        <td>3</td>
        <td>Australia</td>
        <td>12060.33</td>
    </tr>
    <tr>
        <td>3</td>
        <td>Canada</td>
        <td>11826.23</td>
    </tr>
    <tr>
        <td>3</td>
        <td>None</td>
        <td>23886.56</td>
    </tr>
    <tr>
        <td>4</td>
        <td>Australia</td>
        <td>14136.07</td>
    </tr>
    <tr>
        <td>4</td>
        <td>Canada</td>
        <td>14423.39</td>
    </tr>
    <tr>
        <td>4</td>
        <td>None</td>
        <td>28559.46</td>
    </tr>
    <tr>
        <td>5</td>
        <td>Australia</td>
        <td>271.08</td>
    </tr>
    <tr>
        <td>5</td>
        <td>Canada</td>
        <td>243.10</td>
    </tr>
    <tr>
        <td>5</td>
        <td>None</td>
        <td>514.18</td>
    </tr>
    <tr>
        <td>None</td>
        <td>None</td>
        <td>67416.51</td>
    </tr>
    <tr>
        <td>None</td>
        <td>Australia</td>
        <td>33726.77</td>
    </tr>
    <tr>
        <td>None</td>
        <td>Canada</td>
        <td>33689.74</td>
    </tr>
</tbody></table></div>